# Generated by Django 2.2.2 on 2019-06-10 23:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reading_time_local', models.DateTimeField()),
                ('bee_id', models.CharField(max_length=24)),
                ('tid', models.CharField(max_length=24)),
                ('antenna', models.IntegerField()),
                ('pc_id', models.CharField(max_length=100)),
                ('ambient_temperature', models.FloatField()),
                ('pwr_amp_temperature', models.FloatField()),
                ('reader_status', models.IntegerField()),
                ('ms_counter', models.FloatField()),
                ('nb_rssi', models.CharField(max_length=15)),
                ('wb_rssi', models.CharField(max_length=23)),
                ('gain', models.FloatField()),
                ('rssi', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
